### ISSUE TITLE
Not a big issue, and some comments

### ISSUE THREAD

**Issue by Person21** [KRHS-GameProgramming-2016/AstroDigger#3]
It isn't much of an issue, just that the player gets stuck on the blocks rather easily.

That's the only real issue, everything else is just things I noticed. I noticed that while the blocks change color, that is all they do. Not sure if that will change, but it isn't really enough to do anything about. Also the player can shoot through the blocks. Only about three or so at a time, but still. The bullet being invisible will probably change really soon, so I won't actually comment about it.

**Comment by StevenRayno** [comment]
Player now has a new mechanism for firing, Hope you like it better ^_^
